### ISSUE TITLE
It does not have option to open result file in windows file explorer

### ISSUE THREAD

**Issue by garawaa** [kcowolf/rg-gui#13]

**Comment by kcowolf** [comment]
I've created a feature/open-file-location branch which adds an "Open File Location" option to the right-click menu.  Selecting it opens an Explorer window with the file already selected:
![image](https://github.com/kcowolf/rg-gui/assets/23274338/91c1b5ac-10b9-44d0-9b09-39407456932d)

Would that cover what you're looking for?

I'll test it over the next couple days and create a new release after that.

**Comment by kcowolf** [comment]
Merged and released in v0.4.0.
