### ISSUE TITLE
How to support Chinese?

### ISSUE THREAD

**Issue by Asterecho** [kcowolf/rg-gui#6]
i know "rg  -E GBK" can change to support Chinese in cmd.
But i don;t know how to support Chinese in GUI?

**Comment by kcowolf** [comment]
Working on this now.

**Comment by kcowolf** [comment]
@Asterecho Can you try v0.1.5 and see if that works for you?  It adds a combo box to choose a file encoding.  I've only added Auto (RipGrep's default) and GBK so far, but I can add others later.

**Comment by Asterecho** [comment]
> @Asterecho Can you try v0.1.5 and see if that works for you? It adds a combo box to choose a file encoding. I've only added Auto (RipGrep's default) and GBK so far, but I can add others later.

I choose the combo box to GBK，it works well . Thank you very much!
